### ISSUE TITLE
dotnet new classlib doesn't allow to specify a different framework (-f) when using F# (-lang F#) on Ubuntu

### ISSUE THREAD

**Issue by palutz** [dotnet/netcorecli-fsc#103]
When I try to create a class lib with dotnet core and F# on Ubuntu (Linux Mint), it looks like I cannot create the lib with a different Fx than the default while I can do it with C#.
If I write something like this:

> $ dotnet new classlib -f netcoreapp1.0 -lang F# -o ./libTest/

or like this

> $ dotnet new classlib -f netcoreapp1.1 -lang F# -o ./libTest/

I always get an error sayng:

> Invalid input switch:
>   -f

While if I write like this:

> $ dotnet new classlib -f netcoreapp1.1 -o ./libTest/

All works fine (but it will be a C# proj).

If I want to still use _-lang F#_  option, I can remove the -f option and create with the default fx (.Net Standard 1.6) and then manually change the generated .fsproj with these lines:

```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
```

This is my machine data:
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 1.1.0
>   Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

> Distributor ID:	LinuxMint
> Description:	Linux Mint 18.1 Serena
> Release:	18.1
> Codename:	serena
>

**Comment by enricosada** [comment]
@palutz hi, yes `netstandard1.6` was the only option. and was hardcoded in the template (so `-f` wasnt supported).
btw f# lib template (like the others bundled) are in https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-FSharp/Company.ClassLibrary1.fsproj

With sdk `1.0` each template had to use a fixed list of supported target framework (`-f`), but i forgot to add that in the 1.0 templates.

Now with `$(TargetFrameworkOverride)` template property is easier to add more, 

It's fixed with https://github.com/dotnet/templating/commit/a3e41f99e654ba5cbff83ef652d0245f338b799a#diff-a030b9cbe845f5324f44c81483fd56fa who support any `-f`

As you said, workaround is to update the fsproj after is generated.

Closing because can be fixed only with a new release of dotnet/cli (the common templates are bundled in dotnet cli), and next one will contains updated templates anyway.
