### ISSUE TITLE
Change repository name to 'FSharp.NET.Sdk'

### ISSUE THREAD

**Issue by cloudRoutine** [dotnet/netcorecli-fsc#112]
So that it's an accurate indication of the contents of the repo
`netcorecli-fsc` is the name of an obsolete/deprecated project
Plus it's what the people want

![](http://i.imgur.com/MENGN0I.png)

and `netcorecli-fsc` is what they definitely **don't** want.

**Comment by enricosada** [comment]
@cloudRoutine so `netcorecli-fsc` was never a name of anything. I didnt choose it, but i think was good, to bridge `netcorecli` with `fsc`

I'll move all the code inside `fsharp/fsharp` after repo are splitted.
Atm vf# repo infra is too slow otherwise i'll move there before split too, to make it easier to reuse test suite.

I know is a bit annoying for you, sry, but i am closing as `wontfix`.
