### ISSUE TITLE
New console F# project fails with 2.0.0-preview3

### ISSUE THREAD

**Issue by tfb** [dotnet/netcorecli-fsc#120]
Attempting to follow the instructions for creating a new F# console project with dotnet, I got to following:

```
$ dotnet new console -lang f#
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /tmp/fsharp-project/fsharp-project.fsproj...
  Restoring packages for /tmp/fsharp-project/fsharp-project.fsproj...
/tmp/fsharp-project/fsharp-project.fsproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25419-01)
/tmp/fsharp-project/fsharp-project.fsproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-002111-00 ]
  Generating MSBuild file /tmp/fsharp-project/obj/fsharp-project.fsproj.nuget.g.props.
  Generating MSBuild file /tmp/fsharp-project/obj/fsharp-project.fsproj.nuget.g.targets.
  Restore failed in 423.16 ms for /tmp/fsharp-project/fsharp-project.fsproj.


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

```

This is with dotnet-2.0.0-preview3 on Fedora 25.

**Comment by kontomondo** [comment]
@tfb I get the same on Ubuntu

**Comment by enricosada** [comment]
Hi, so:

`2.0.0-preview3` is not yet released, is a development version. if you want to use that (is normal for dev version), you need to create a `nuget.config` and add the `.net core myget feed` (the packages needed are not in nuget.org, so `dotnet restore` doest find it). follow the info in https://github.com/dotnet/cli/issues/6581#issuecomment-301326553

**Best option** probably you want to use the release `2.0.0-preview2` (more info in [download archive here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md)) who works ootb because package are already on nuget.org

As a note, starting from `sdk 2.0`, the F# integration bundled with `microsoft.net.sdk` (not external in `fsharp.net.sdk`, this repo) all the issues should be filled in https://github.com/dotnet/cli/issues . 
But np, feel free to open here, will more it if needed
