### ISSUE TITLE
FSharp.NET.Sdk nuget package has unnecessary dep restrictions for FSharp.Compiler.Tools

### ISSUE THREAD

**Issue by jbtule** [dotnet/netcorecli-fsc#121]
In FSharp.NET.Sdk v1.0.5 nuget package the dependencies are listed in conditional groups:

```
  <dependencies>
            <group targetFramework=".NETStandard1.3">
                <dependency id="FSharp.Compiler.Tools" version="4.1.17" />
            </group>
            <group targetFramework=".NETFramework4.0">
                <dependency id="FSharp.Compiler.Tools" version="4.1.17" />
            </group>
        </dependencies>
```

I'm not sure why, they are the same dependency and `fsharp.compiler.tools` doesn't have any target framework restrictions itself. 

This causes an omission when targeting say a [multi-target with a portable library](https://stackoverflow.com/questions/44979449/net-multi-target-with-net-standard-and-portable-library-msbuild-15). 

While it is an easy work around, just by adding the `PackageReference` directly  and then it does indeed work for targeting PCL libraries new sdk on [Mac](https://travis-ci.org/fsprojects/FSharp.Interop.Dynamic/builds/251057399) and [Windows](https://ci.appveyor.com/project/jbtule/fsharp-dynamic-832/build/70), it seems needless.

**Comment by enricosada** [comment]
Hi @jbtule ,

the `fsharp.net.sdk` package is to be used only with new [.net sdk](https://github.com/dotnet/sdk). 
The .net sdk (the new csproj/fsprj) doesnt support Portable libraries, these are deprecated, in favor of `netstandard` target framework

The `fsharp.net.sdk` package contains only the integration needed for new sdk, the rest (compiler/etc) is as usual in `fsharp.compiler.tools`. so afaik compiler restriction are enough.

Maybe you should reopen this discussion in https://github.com/microsoft/visualfsharp/ repo to ask for guidance about this scenario, also because in sdk 2.0, the F# support will be embedded in `microsoft.net.sdk` (so not this repo), and managed directly by MS teams

Feel free to reopen or link this issue

**Comment by jbtule** [comment]
It's your FSharp.NET.Sdk nuget package dependency listing that's this issue. 
why not just plain this

```
  <dependencies>
       <dependency id="FSharp.Compiler.Tools" version="4.1.17" />
 </dependencies>
```
