### ISSUE TITLE
Support for F# library types

### ISSUE THREAD

**Issue by mantzas** [dotnet/netcorecli-fsc#15]
Hi,

i am trying to generate with the cli a library for F#. there is a workaround in [FAQ](https://github.com/dotnet/netcorecli-fsc/wiki/FAQ) but i cannot get it to work. And VS has nothing yet to support that either. Any ideas?

**Comment by enricosada** [comment]
can you add more info about the error? or link the source code if it's open source.

You can find example for lib/console project in this repo:

- [.net core sdk preview1 examples](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview1)
- [.net core sdk preview2 examples](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview2)

**Comment by mantzas** [comment]
your samples above work fine, and i got it to work. Will there be support for creating a library fro command line like in c#? (dotnet new -t Lib)

**Comment by enricosada** [comment]
@mantzas fixed by version `1.0.0-preview2-003131` of .net core sdk (ref [announcement](https://blogs.msdn.microsoft.com/dotnet/2016/09/13/announcing-september-2016-updates-for-net-core-1-0/) )

the new sdk version is compatible with current `project.json` and can be also installed side by side (like every .net core sdk)

so

```
dotnet new -l fsharp
dotnet restore
dotnet run
```

works

**Comment by mantzas** [comment]
@enricosada nice thanks very much
