### ISSUE TITLE
VS Code basic usage

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#29]
It's an high level task, project affected can be [ionide](https://github.com/ionide/ionide-vscode-fsharp) or a dependency like [FsAutoComplete](https://github.com/ionide/FsAutoComplete).

If possible work should be merged in the base repo (like https://github.com/fsharp/FsAutoComplete)

- https://github.com/ionide/ionide-vscode-fsharp/issues/277 mono is **not required** for .net core only
- replace `ProjectCracker` with whatever omnisharp is using (msbuild as library, dunno) so is aligned with c# (more future proof, less hacks)
- https://github.com/dotnet/netcorecli-fsc/issues/35 debuggin of .net core (`netcoreapp1.0`) projects
- works with app with project references ( like `console` + `lib` ), like a solution (or with .sln), support msbuild15 fsproj ootb (ref https://github.com/fsharp/FsAutoComplete/issues/137 )
- fix https://github.com/ionide/ionide-vscode-fsharp/issues/312 so will work without requiring a build before opening VS Code.

**Comment by cloudRoutine** [comment]
I've already been working on an alternative project reading mechanism for my [ProtoWorkspace]() that is based on Omnisharp's approach.

- [Project, Solution, & ProjectFileInfo Type Extensions](https://github.com/fsharp-editing/ProtoWorkspace/blob/master/ProtoWorkspace/Extensions.fs#L62-L158)
- [SolutionFileInfo.fs](https://github.com/fsharp-editing/ProtoWorkspace/blob/master/ProtoWorkspace/SolutionFileInfo.fs)
- [ProjectFileInfo.fs](https://github.com/fsharp-editing/ProtoWorkspace/blob/master/ProtoWorkspace/ProjectFileInfo.fs)

The issue I've run into with this is that F#'s lack of an [`extern alias`](https://github.com/fsharp/fslang-suggestions/issues/513) means that some hoops will need to be jumped through in order to support reading both the old and new fsproj formats. Unless we want to [build the migration functionality](https://github.com/dotnet/netcorecli-fsc/issues/30) into this new project config reader in order to force everyone to update to the format.

If we pull this functionality out into a standalone tool I think we should merge it into [FSharp.Compiler.Service](https://github.com/fsharp/FSharp.Compiler.Service) replacing the projectcracker, not into FSAC. FSAC can use the dependency to get the functionality.


- [msbuild myget feed](https://dotnet.myget.org/gallery/msbuild)

**Comment by cloudRoutine** [comment]
I just finished knocking out a basic project inspector that reads project options out of the new fsproj files

[fsprojectile](https://github.com/fsharp-editing/fsprojectile)

The net46 build is the fully featured version that makes use of FCS, but since that isn't netcore compatible the netcore version uses a shim instead

**Comment by czifro** [comment]
May I make a suggestion? I think it would be nice, provided vscode offers the api, to order fs files in the left panel of vscode according to the compile order: 

Compile order:

![screenshot 2017-01-01 14 22 59](https://cloud.githubusercontent.com/assets/5378541/21583257/f1ea8a80-d02d-11e6-8669-ab7a18af1ae1.png)

Displayed order:

![screenshot 2017-01-01 14 22 27](https://cloud.githubusercontent.com/assets/5378541/21583261/31f5d080-d02e-11e6-849b-b8c464e188ac.png)

I figured that if there is a move to do project inspection, then this would a helpful feature, especially since VS 20xx offers this (as well as Xamarin).

**Comment by enricosada** [comment]
@czifro custom treeview in vscode, to reflect Compile items is tracked in https://github.com/ionide/ionide-vscode-fsharp/issues/248

**Comment by czifro** [comment]
@enricosada thank you for the correction!

**Comment by enricosada** [comment]
Done, works in ionide 2.25.1.

atm require mono installed on non windows os (FSAC require it).

![recf-ionide2](https://cloud.githubusercontent.com/assets/147243/24086074/a63d34d0-0d08-11e7-8ca4-a503aecc8cb4.gif)
