### ISSUE TITLE
'dotnet-migrate' support for project.json ->  fsproj

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#38]
The `dotnet-migrate` doesnt support F# yet, to convert `project.json` to `fsproj`

WORKROUND: see https://github.com/dotnet/netcorecli-fsc/wiki/How-to-migrate-preview2-projects-to-rc3 tutorial

How to implement that:

If someone want to do that, i added a branch https://github.com/enricosada/cli/tree/dotnet_migrate_fsharp to start (you can develop on you own branch and send pr there, my branch it's just to make thing moving).
Write a comment, i'll assign to you if you want

Added:

- consider project.json with `compilerName: fsc` (so f# projects)

Atm will convert an f# project.json -> csproj.

TODO:

- generate with `.fsproj` extension
- fix fsproj with the things we need (see template diff between `dotnet new` and `dotnet new --lang fsharp`)
   - add `FSharp.NET.Sdk` packagereference
   - add Sdk="FSharp.NET.Sdk" before "Microsoft.NET.Sdk"
   - add dotnet-compile-fsc tool reference
- check projectreference works
- **add tests inside dotnet/cli**, of minimal migration project.json (console at least, lib too better) -> migrate -> dotnet run should pass. Importnatn because template may change (an will for rtm a bit)

all the changes should be inside dotnet-migrate and `dotnet/cli` repo

**Comment by cloudRoutine** [comment]
### dotnet cli reference code

- [dotnet-migrate](https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-migrate)
- [Microsoft.DotNet.ProjectJsonMigration](https://github.com/dotnet/cli/tree/rel/1.0.0-preview3/src/Microsoft.DotNet.ProjectJsonMigration)
- [Microsoft.DotNet.ProjectJsonMigration.Tests](https://github.com/dotnet/cli/tree/rel/1.0.0/test/Microsoft.DotNet.ProjectJsonMigration.Tests)
- [ProjectJsonToCSProj.md](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md)

**Comment by enricosada** [comment]
If someone want to do that, i added a branch https://github.com/enricosada/cli/tree/dotnet_migrate_fsharp to start (you can develop on you own branch and send pr there, my branch it's just to make thing moving)

Added:

- consider project.json with `compilerName: fsc` (so f# projects)

Atm will convert an f# project.json -> csproj.

TODO:

- generate with `.fsproj` extension
- fix fsproj with the things we need
   - add `FSharp.NET.Sdk` packagereference
   - change at end the `Microsoft.Csharp.target` to `Microsoft.Common.target` (see templates)
- add tests (inside dotnet/cli), minimal for `console`/`lib`

all the changes should be inside dotnet-migrate and `dotnet/cli` repo

**Comment by tlycken** [comment]
Yo!

I'm trying to build the latest version pf dotnet/netcorecli from source in order to address this, but the build fails.

This is what i've done:

1. installed `cmake` (and added to PATH)
2. clone `dotnet\netcorecli` (ended up on the `rel\1.0` branch by default)
3. run `build.cmd`

but the build fails with a bunch of errors about attribute duplicates in `AssemblyInfo` files. Am I missing something here?

**Comment by tlycken** [comment]
Yo!

I'm trying to build the latest version from source (eventually in order to address https://github.com/dotnet/netcorecli-fsc/issues/38), but the build fails.

This is what i've done:

1. installed `cmake` (and added to PATH)
2. clone `dotnet\netcorecli` (ended up on the `rel\1.0` branch by default)
3. run `build.cmd`

but the build fails with a bunch of errors about duplicate attributes in AssemblyInfo files. I've tried @enricosada's branch https://github.com/enricosada/cli/tree/dotnet_migrate_fsharp too, with the same result.

Am I missing something in my toolchain here, or is this a legitimate error in the source?

**Comment by enricosada** [comment]
Really sorry @tlycken , i didint see the notification about your comment. Thx a lot for trying to implement that.

I never had your issue building https://github.com/dotnet/cli repository.
But your flow was ok, i can just link the developer doc about that (maybe there is a step you missed?) https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md
Anyway open an issue in https://github.com/dotnet/cli with the error message, they can help for sure.

**Comment by enricosada** [comment]
closing, all project are already migrate to new sdk or can do that using the tutorial.
