### ISSUE TITLE
No .pdb is produced when DebugType is full.

### ISSUE THREAD

**Issue by DaveEmmerson** [dotnet/netcorecli-fsc#89]
dotnet new console
dotnet restore
dotnet build

This works, producing a c# result with a portable .pdb

Change the DebugType to full in the .csproj and restore/rebuild it you get a windows .pdb.

dotnet new console -lang f#
dotnet restore
dotnet build

This works, producing a f# result with a portable .pdb

Change the DebugType to full in the .fsproj and no .pdb is produced.

I've searched around and can't find any mention of this issue. Should it work or does the f# side of things not allow for the 'full' windows .pdbs?

**Comment by DaveEmmerson** [comment]
This is on:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

msbuild is 15.1.548.43366

**Comment by enricosada** [comment]
@DaveEmmerson hi.

So i tried, and can repro. The arguments are passed correctly to fsc compiler (`--debug:full`, easier to check with `dotnet build -v n`), but full pdb seems not supported by fsc netcore (the one used) atm.

i created an issues in visualfsharp repo (because is a fsc bug) because i expected at least a warning/error. (ref https://github.com/Microsoft/visualfsharp/issues/2565 )

Added to known issues in wiki https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1#cannot-produce-full-pdb 

Closing this issue because is not related to sdk binding itself, but an fsc compiler issue, so discussion will continue in linked issue.

**Comment by DaveEmmerson** [comment]
Thanks for sorting out the report for the other side. Wasn't sure where to
log it initially.

**Comment by enricosada** [comment]
@DaveEmmerson  feel free to open issue here if relate to .net core sdk.
I'll forward to microsoft/visualfsharp if it's not an issue of this repo, np 😄 
thx for bugreport, at least i added a known issue
