### ISSUE TITLE
StackOverflowException when compiling with latest SDK in Debug mode

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/netcorecli-fsc#98]
After upgrading and building Fable with latest FSharp.NET.Sdk (1.0.2) I started getting StackOverflowExceptions when compiling big projects (the F# compiler itself). I've tried to debug the problem in many ways but I didn't find the cause until I realized that going back ttoFSharp.NET.Sdk 1.0.0-beta-060000 fixed the problem. It also seems that the latest version works if the Release config is used instead.

Is this intended? What are the options in Debug config that can cause the stack overflow, just `--optimize-`?

**Comment by enricosada** [comment]
@alfonsogarciacaro so, just do `dotnet build -v n` to see fsc args.

If is fsc who crash, open a bug in https://github.com/microsoft/visualfsharp/ repo, because is a regression with fsc, so is important.
The old `FSharp.NET.Sdk` referenced a previous version of fsc, just check `dotnet build -v n` paths.
you can also try new sdk with old fsc, just set `<FscToolPath>` property in msbuild (do `dotnet build -v diag` to show all properties, but is really verbose so redirect to file :D).

Please close this after you open a bug in vf# repo

**Comment by alfonsogarciacaro** [comment]
Actually I was wrong, I'm getting the StackOverflow exception even when compiling in Release mode :grin: I'll report the problem in the VF# repo, thanks!

**Comment by alfonsogarciacaro** [comment]
@enricosada The problem doesn't happen with FSharp.Compiler.Tools 4.1.0. Would it be possible to release a new FSharp.NET.Sdk that is tied to that version? It's the only way I have to use intellisense with Ionide at the moment :/

**Comment by enricosada** [comment]
Sure, just add `FscToolPath` Property in the fsproj pointing to previous fsc directory. 
So fsproj use new msbuild task (for intelllisense) an d previous compiler (without bug)
Let me write and example tomorrow morning

**Comment by alfonsogarciacaro** [comment]
Thanks, that's working! :clap: I have added the FSharp.Compiler.Tools to the repo to avoid absolute paths ([commit](https://github.com/fable-compiler/Fable/commit/d6fd9259d1e50ef40a0bd867f02fd63aa84a02e7)), not sure if that's the best way :)

BTW, the issue has been reported here: https://github.com/Microsoft/visualfsharp/issues/2682
